export const FETCH_GOODS_START = "FETCH_GOODS_START";
export const FETCH_GOODS_SUCCESS = "FETCH_GOODS_SUCCESS";
export const FETCH_GOODS_FAILURE = "FETCH_GOODS_FAILURE";

export const LOAD_MORE_GOODS_START = "LOAD_MORE_GOODS_START";
export const LOAD_MORE_GOODS_SUCCESS = "LOAD_MORE_GOODS_SUCCESS";
export const LOAD_MORE_GOODS_FAILURE = "LOAD_MORE_GOODS_FAILURE";
