export const banner = [
  {
    img: "img/sofa.png",
    title: "Don’t worry, sit happy!",
    subtitle: "Up to 15% off* couch",
    period: "August 15 - September 21",
    position: "right"
  },
  {
    img: "img/banner_cheir.png",
    title: "Living in style",
    subtitle: "Check our special offers to armchairs ",
    period: "Only to 21 Oktober",
    position: "left",
    size: "small"
  },
  {
    img: "img/banner_sofa@2x.png",
    title: "Don’t worry, relax happy!",
    subtitle: "Up to 35% off* couch",
    period: "August 02 - September 11",
    position: "right",
    size: "medium"
  }
];

export const newProducts = {
  img: "img/catalog.png",
  title: "The 2020 IKEA Catalogue is here!",
  text:
    "There’s so much to know about IKEA beyond our low-price furniture. From our sustainable sourcing of cotton and wood, to our stance on human rights; what it’s like to work for IKEA, to our democratic design approach",
  period: "August 15 - September 21"
};

export const footerMenuData = [
  { title: "Contact us" },
  { title: "IKEA Planners" },
  { title: "Customer Service" },
  { title: "Guest purchase" },
  { title: "Gift Card" },
  { title: "IKEA Family" },
  { title: "Returns" },
  { title: "Payments" },
  { title: "FAQ" }
];

export const productData = [
  {
    id: "1",
    img: "img/basket",
    tag: "",
    title: "KNAGGLIG",
    subtitle: "Plant pot, indoor/outdoor gray, 3 ½ ",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#CCAB00", "#665500"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "Home safety",
    material: "Ancient cherry"
  },
  {
    id: "2",
    img: "img/basket_2",
    tag: "Sale",
    title: "STORSTABBE",
    subtitle: "Box, pine, 23x31x15 cm",
    rate: "5.0/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    votes: "18 votes",
    status: true,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Home improvement",
    material: "Scandinavian Oak"
  },
  {
    id: "3",
    img: "img/bed_box",
    tag: "",
    title: "GNABBAS",
    subtitle: "Box with handle, acacia",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: true,
    fullPrice: "10$",
    salePrice: "",
    category: "IKEA Food",
    material: "Olive palm"
  },
  {
    id: "4",
    img: "img/box",
    tag: "Sale",
    title: "SKOGSTA",
    subtitle: "9-bottle wine rack, solid wood",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Storage & Home Organization",
    material: "Ancient cherry"
  },
  {
    id: "5",
    img: "img/box_2",
    tag: "Sale",
    title: "HUTTEN",
    subtitle: "Basket, rattan, 32x34x32 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Laundry & cleaning",
    material: "Scandinavian Oak"
  },
  {
    id: "6",
    img: "img/flower_box",
    tag: "Sale",
    title: "BRANÄS",
    subtitle: "Basket, seagrass, 25 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Home safety",
    material: "Olive palm"
  },
  {
    id: "7",
    img: "img/grey_pot",
    tag: "",
    title: "FLÅDIS",
    subtitle: "Plant pot with holder, indoor/outdoor, white, 6 ",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "Home improvement",
    material: "Ancient cherry"
  },
  {
    id: "8",
    img: "img/handle_box",
    tag: "Sale",
    title: "KNIPSA",
    subtitle: "Laundry basket, 50 l",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "IKEA Food",
    material: "Scandinavian Oak"
  },
  {
    id: "9",
    img: "img/laundry_basket",
    tag: "",
    title: "MOPPE",
    subtitle: "Box, pine, 23x31x15 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "Storage & Home Organization",
    material: "Olive palm"
  },
  {
    id: "10",
    img: "img/mini_chest",
    tag: "Sale",
    title: "BRANKIS",
    subtitle: "Box with lid, beige, 25x35x15 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Laundry & cleaning",
    material: "Ancient cherry"
  },
  {
    id: "11",
    img: "img/nightstand",
    tag: "Sale",
    title: "RÅGRUND",
    subtitle: "Basket, 32x35x32 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Home safety",
    material: "Scandinavian Oak"
  },
  {
    id: "12",
    img: "img/oval_basket",
    tag: "",
    title: "RÖMSKOG",
    subtitle: "Box with handle, acacia",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "Home improvement",
    material: "Olive palm"
  },
  {
    id: "13",
    img: "img/plant",
    tag: "",
    title: "BRANÄS",
    subtitle: "9-bottle wine rack, solid wood",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "IKEA Food",
    material: "Ancient cherry"
  },
  {
    id: "14",
    img: "img/rack_chair",
    tag: "",
    title: "BRANÄS",
    subtitle: "Basket, rattan, 32x34x32 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "Storage & Home Organization",
    material: "Scandinavian Oak"
  },
  {
    id: "15",
    img: "img/rack",
    tag: "",
    title: "BRANÄS",
    subtitle: "Basket, seagrass, 25 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Laundry & cleaning",
    material: "Olive palm"
  },
  {
    id: "16",
    img: "img/white_pot",
    tag: "Sale",
    title: "BRANÄS",
    subtitle: "Basket, seagrass, 32x33x32 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Home safety",
    material: "Ancient cherry"
  },
  {
    id: "17",
    img: "img/rack",
    tag: "Sale",
    title: "FLÅDIS",
    subtitle: "Mini chest of drawers, birch plywood",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Home improvement",
    material: "Scandinavian Oak"
  },
  {
    id: "18",
    img: "img/rack",
    tag: "",
    title: "HUTTEN",
    subtitle: "Laundry basket, 50 l",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "IKEA Food",
    material: "Olive palm"
  },
  {
    id: "19",
    img: "img/rack",
    tag: "",
    title: "SKURAR",
    subtitle: "Towel rack chair, bamboo",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "",
    category: "Storage & Home Organization",
    material: "Ancient cherry"
  },
  {
    id: "20",
    img: "img/rack",
    tag: "Sale",
    title: "BRANÄS",
    subtitle: "Bed storage box, rattan, 65x70 cm",
    rate: "4.5/5.0",
    size: ["210*60*30", "210*70*20", "180*80*40"],
    color: ["#72520D", "#C6B082"],
    status: false,
    fullPrice: "10$",
    salePrice: "5$",
    category: "Laundry & cleaning",
    material: "Scandinavian Oak"
  }
];

export const slides = [{}, {}, {}, {}];
